#!/usr/bin/env bash
set -euo pipefail
theme_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
required=(style.css functions.php header.php footer.php front-page.php page-listing.php page-about.php page-faq.php page-contact-us.php assets/css/app.css assets/js/app.js)
for file in "${required[@]}"; do
  test -s "$theme_dir/$file" || { echo "Missing required file: $file" >&2; exit 1; }
done
rg -q "Theme Name: Auto Point Motor Group" "$theme_dir/style.css"
rg -q "register_post_type\('vehicle'" "$theme_dir/functions.php"
test -s "$theme_dir/inc/catalog.php" || { echo "Missing required file: inc/catalog.php" >&2; exit 1; }
test -s "$theme_dir/inc/seo.php" || { echo "Missing required file: inc/seo.php" >&2; exit 1; }
test -s "$theme_dir/inc/performance.php" || { echo "Missing required file: inc/performance.php" >&2; exit 1; }
test -s "$theme_dir/inc/import-command.php" || { echo "Missing required file: inc/import-command.php" >&2; exit 1; }
rg -Fq "require_once APMG_DIR . '/inc/seo.php'" "$theme_dir/functions.php"
rg -Fq "require_once APMG_DIR . '/inc/performance.php'" "$theme_dir/functions.php"
rg -Fq 'function apmg_meta_description' "$theme_dir/inc/seo.php"
rg -Fq '<link rel="canonical"' "$theme_dir/inc/seo.php"
rg -Fq "'/llms.txt'" "$theme_dir/inc/seo.php"
rg -Fq "wp_sitemaps_post_types" "$theme_dir/inc/seo.php"
rg -Fq "wp_sitemaps_add_provider" "$theme_dir/inc/seo.php"
rg -Fq "'woocommerce-general'" "$theme_dir/inc/performance.php"
rg -Fq 'wp_dequeue_style($handle)' "$theme_dir/inc/performance.php"
rg -Fq "'woocommerce'" "$theme_dir/inc/performance.php"
rg -Fq "'woocommerce-tokenization-form'" "$theme_dir/inc/performance.php"
rg -Fq 'wp_dequeue_script($handle)' "$theme_dir/inc/performance.php"
rg -Fq 'function apmg_flush_page_cache' "$theme_dir/inc/performance.php"
rg -Fq "add_action('save_post_vehicle', 'apmg_flush_page_cache')" "$theme_dir/inc/performance.php"
rg -Fq "add_action('updated_post_meta', 'apmg_flush_page_cache_for_meta'" "$theme_dir/inc/performance.php"
rg -Fq 'function apmg_generate_performance_images' "$theme_dir/inc/performance.php"
rg -Fq "add_filter('wp_generate_attachment_metadata', 'apmg_generate_performance_images'" "$theme_dir/inc/performance.php"
rg -Fq 'function apmg_performance_image_url' "$theme_dir/inc/performance.php"
rg -Fq 'set_url_scheme($url, wp_parse_url(home_url' "$theme_dir/inc/performance.php"
rg -Fq "'.avif'" "$theme_dir/inc/performance.php"
rg -Fq "'image/avif'" "$theme_dir/inc/performance.php"
rg -Fq "\$quality = \$variant === 'hero' ? 50 : 45" "$theme_dir/inc/performance.php"
rg -Fq "add_filter('wp_editor_set_quality', \$avif_quality, 10, 2)" "$theme_dir/inc/performance.php"
rg -Fq "remove_filter('wp_editor_set_quality', \$avif_quality, 10)" "$theme_dir/inc/performance.php"
rg -Fq "'vehicle_make'" "$theme_dir/inc/catalog.php"
rg -Fq "'vehicle_model'" "$theme_dir/inc/catalog.php"
rg -Fq "'vehicle_fuel'" "$theme_dir/inc/catalog.php"
rg -Fq "'vehicle_transmission'" "$theme_dir/inc/catalog.php"
rg -Fq "'vehicle_body'" "$theme_dir/inc/catalog.php"
rg -Fq "'vehicle_colour'" "$theme_dir/inc/catalog.php"
rg -Fq "register_post_meta('vehicle', \$key" "$theme_dir/inc/catalog.php"
rg -Fq "'apmg_price'" "$theme_dir/inc/catalog.php"
rg -Fq "WP_CLI::add_command('apmg import-vehicles'" "$theme_dir/inc/import-command.php"
rg -Fq "\$vehicle['images']" "$theme_dir/inc/import-command.php"
rg -q "template-parts/vehicle-catalog" "$theme_dir/front-page.php"
rg -q "get_permalink" "$theme_dir/template-parts/vehicle-card.php"
rg -Fq "'image_id' =>" "$theme_dir/inc/catalog.php"
rg -Fq 'wp_get_attachment_image' "$theme_dir/template-parts/vehicle-card.php"
rg -Fq '<picture>' "$theme_dir/template-parts/vehicle-card.php"
rg -q "apmg_gallery_urls" "$theme_dir/single-vehicle.php"
rg -q 'data-gallery-prev' "$theme_dir/single-vehicle.php"
rg -q 'data-gallery-next' "$theme_dir/single-vehicle.php"
rg -Fq '.vehicle-gallery__arrow' "$theme_dir/src/input.css"
! rg -Fq 'IntersectionObserver' "$theme_dir/assets/js/app.js"
! rg -Fq 'motion-reveal' "$theme_dir/src/input.css"
rg -Fq '.inventory-card:hover::after' "$theme_dir/src/input.css"
rg -Fq '@keyframes gallery-slide-next' "$theme_dir/src/input.css"
rg -Fq '@media (prefers-reduced-motion: reduce)' "$theme_dir/src/input.css"
rg -q "\(066\) 710 2545" "$theme_dir/header.php"
rg -q "logo.svg" "$theme_dir/header.php"
rg -Fq "home_url('/finance/')" "$theme_dir/header.php"
rg -Fq "home_url('/exchange/')" "$theme_dir/header.php"
! rg -Fq 'href="#"' "$theme_dir/footer.php"
! rg -Fq '<h1 class="ribbon-title">' "$theme_dir/home.php"
rg -q "tailwindcss" "$theme_dir/package.json"
rg -Fq 'BROWSERSLIST_IGNORE_OLD_DATA=1' "$theme_dir/package.json"
test -s "$theme_dir/assets/fonts/fa-solid-900.woff2" || { echo "Missing local Font Awesome solid font." >&2; exit 1; }
test -s "$theme_dir/assets/fonts/fa-brands-400.woff2" || { echo "Missing local Font Awesome brands font." >&2; exit 1; }
if rg -q 'fonts\.googleapis\.com|use\.fontawesome\.com' "$theme_dir/functions.php"; then
  echo "Theme assets must not depend on render-blocking third-party font stylesheets." >&2
  exit 1
fi
rg -Fq '@font-face' "$theme_dir/src/input.css"
rg -Fq 'data:font/woff2;base64,' "$theme_dir/src/input.css"
rg -Fq 'data:font/woff2;base64,' "$theme_dir/assets/css/app.css"
! rg -Fq 'undefined' "$theme_dir/assets/css/app.css"
rg -Fq 'wp_add_inline_style' "$theme_dir/functions.php"
rg -q "template-parts/home-search-hero" "$theme_dir/front-page.php"
rg -q "Your next car starts here" "$theme_dir/template-parts/home-search-hero.php"
rg -q 'class="brand-hero__media"' "$theme_dir/template-parts/home-search-hero.php"
rg -Fq '<picture>' "$theme_dir/template-parts/home-search-hero.php"
rg -q 'wp_get_attachment_image' "$theme_dir/template-parts/home-search-hero.php"
if rg -Fq 'wp_kses_post(wp_get_attachment_image' "$theme_dir/template-parts/home-search-hero.php"; then
  echo "Hero image attributes must not be stripped by wp_kses_post." >&2
  exit 1
fi
rg -Fq "'fetchpriority' => 'high'" "$theme_dir/template-parts/home-search-hero.php"
rg -Fq "'sizes' => '100vw'" "$theme_dir/template-parts/home-search-hero.php"
! rg -q 'brand-hero__mark' "$theme_dir/template-parts/home-search-hero.php"
rg -Fq '.brand-hero__media img' "$theme_dir/src/input.css"
rg -Fq 'linear-gradient(90deg, rgba(5,20,50' "$theme_dir/src/input.css"
rg -q 'name="vehicle_search"' "$theme_dir/template-parts/home-search-hero.php"
rg -q 'class="hero-search__field"' "$theme_dir/template-parts/home-search-hero.php"
! rg -q '<select' "$theme_dir/template-parts/home-search-hero.php"
! rg -q 'name="make"\|name="model"' "$theme_dir/template-parts/home-search-hero.php"
rg -q '@keyframes hero-search-border' "$theme_dir/src/input.css"
rg -q 'name="transmission\[\]"' "$theme_dir/template-parts/vehicle-filters.php"
rg -q 'name="fuel\[\]"' "$theme_dir/template-parts/vehicle-filters.php"
rg -q 'name="price_min"' "$theme_dir/template-parts/vehicle-filters.php"
rg -q 'name="year_min"' "$theme_dir/template-parts/vehicle-filters.php"
rg -q 'id="inventory-sort"' "$theme_dir/template-parts/vehicle-catalog.php"
rg -q 'name="orderby"' "$theme_dir/template-parts/vehicle-catalog.php"
rg -q 'update_post_thumbnail_cache' "$theme_dir/template-parts/vehicle-catalog.php"
rg -Fq '.inventory-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr));' "$theme_dir/src/input.css"
rg -Fq '.inventory-card__image { position: relative; display: block; aspect-ratio: 16 / 10;' "$theme_dir/src/input.css"
rg -Fq '.inventory-card__subtitle' "$theme_dir/src/input.css"
rg -Fq -- '-webkit-line-clamp: 2' "$theme_dir/src/input.css"
rg -q 'get_the_terms' "$theme_dir/inc/catalog.php"
rg -q 'WP_CLI::error' "$theme_dir/inc/import-command.php"
rg -q 'apmg_cover_source_url' "$theme_dir/inc/import-command.php"
rg -Fq 'array_merge([$vehicle' "$theme_dir/single-vehicle.php"
rg -q "Buying with Autopoint Motor Group" "$theme_dir/front-page.php"
test -s "$theme_dir/template-parts/google-reviews.php" || { echo "Missing Google reviews section" >&2; exit 1; }
rg -q "template-parts/google-reviews" "$theme_dir/front-page.php"
rg -Fq '4.7' "$theme_dir/template-parts/google-reviews.php"
rg -Fq '300+ Google reviews' "$theme_dir/template-parts/google-reviews.php"
rg -Fq 'ChIJV0EZKiM1RUgRxOwTQvHY8N0' "$theme_dir/template-parts/google-reviews.php"
rg -Fq 'search.google.com/local/writereview' "$theme_dir/template-parts/google-reviews.php"
rg -Fq 'class="google-reviews__stars" role="img"' "$theme_dir/template-parts/google-reviews.php"
rg -Fq 'class="google-reviews__card-stars" role="img"' "$theme_dir/template-parts/google-reviews.php"
rg -Fq '.google-reviews' "$theme_dir/src/input.css"
rg -Fq '.brand-footer__bottom a { color: #4f5d76; }' "$theme_dir/src/input.css"
rg -Fq 'color: #56627a; font-size: 10px;' "$theme_dir/src/input.css"
rg -q "Celebrating 30 years" "$theme_dir/front-page.php"
rg -q "\.vehicle-gallery, \.vehicle-summary.*min-width: 0" "$theme_dir/src/input.css"
! rg -q "update_option\('blogname', 'Autocar'" "$theme_dir/functions.php"
rg -q "update_option\('blogname', 'Autopoint Motor Group'" "$theme_dir/functions.php"
rg -q "Dromthacker, Tralee" "$theme_dir/page-contact-us.php"
rg -q "30 years" "$theme_dir/page-about.php"
rg -q "brand-page-hero" "$theme_dir/template-parts/page-hero.php"
! rg -q "Autocar Street\|+620 874\|info@autocar" "$theme_dir/page-contact-us.php"
! rg -q "sell my car to Autocar" "$theme_dir/page-faq.php"
test -s "$theme_dir/plugins/apmg-commerce/apmg-commerce.php" || { echo "Missing APMG Commerce plugin" >&2; exit 1; }
rg -Fq 'apmg_commerce_status' "$theme_dir/plugins/apmg-commerce/src/Bridge/WordPressVehicleRepository.php"
rg -Fq 'sale_pending' "$theme_dir/plugins/apmg-commerce/src/Domain/Status.php"
rg -Fq 'apmg_start_checkout' "$theme_dir/template-parts/vehicle-commercial-actions.php"
rg -Fq 'apmg_commerce_form_url' "$theme_dir/template-parts/vehicle-commercial-actions.php"
php "$theme_dir/tests/vehicle-search.php"
php "$theme_dir/tests/catalog-domain.php"
php "$theme_dir/tests/reference-parser.php"
php "$theme_dir/tests/reference-catalog.php"
php "$theme_dir/tests/image-import.php"
php "$theme_dir/tests/page-cache.php"
node "$theme_dir/tests/vehicle-gallery.js"
node "$theme_dir/tests/motion.js"
php "$theme_dir/plugins/apmg-commerce/tests/commerce/run.php"
php "$theme_dir/plugins/apmg-commerce/tests/run.php"
echo "Theme contract passed."
